volumes:
  mysql_data:

networks:
  mynet:
    driver: bridge

services:
  go-user-api:
    build: .
    image: go-user-api:latest
    container_name: go-user-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - mynet
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: "128M"
        limits:
          cpus: "0.2"
          memory: "256M"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_user_api
    ports:
      - "3306:3306"
    networks:
      - mynet
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: "0.1"
          memory: "128M"
        limits:
          cpus: "0.2"
          memory: "256M"